import {
  Snowflake,
  Accessibility,
  Sun,
  Box,
  Waves,
  Flame,
  Shield,
  ArrowUpDown,
  ShieldCheck,
  GripVertical,
  Dog,
  Building2,
  Home,
} from 'lucide-react';

export const ALL_AMENITIES = [
  { key: 'ac', label: 'מיזוג', icon: Snowflake },
  { key: 'handicap', label: 'גישה לנכה', icon: Accessibility },
  { key: 'solarHeater', label: 'דוד שמש', icon: Sun },
  { key: 'storage', label: 'מחסן', icon: Box },
  { key: 'sunBalcony', label: 'מרפסת שמש', icon: Waves },
  { key: 'boiler', label: 'דוד', icon: Flame },
  { key: 'mamad', label: 'ממ״ד', icon: Shield },
  { key: 'elevator', label: 'מעלית', icon: ArrowUpDown },
  { key: 'mamak', label: 'ממ״ק', icon: ShieldCheck },
  { key: 'bars', label: 'סורגים', icon: GripVertical },
  { key: 'pets', label: 'חיות מחמד', icon: Dog },
  { key: 'housingUnit', label: 'יחידת דיור', icon: Building2 },
  { key: 'shelter', label: 'מקלט בבניין', icon: Home },
];
