// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma v7+: connection URL for Migrate lives here (NOT in schema.prisma).
    // Keep this CI-friendly by providing a safe default for SQLite projects.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
