import { PrismaClient } from '@prisma/client'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import bcrypt from 'bcryptjs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const dbPath = path.join(__dirname, '..', 'dev.db')
console.log('📦 Database path:', dbPath)

const adapter = new PrismaBetterSqlite3({ url: `file:${dbPath}` })
const prisma = new PrismaClient({ adapter })

const username = process.env.ADMIN_USERNAME || 'admin'
const password = process.env.ADMIN_PASSWORD || 'admin123'

async function main() {
  console.log('🌱 Starting seed...\n')

  // ===== 1. Create Admin User =====
  const existingUser = await prisma.user.findUnique({ where: { username } })
  if (existingUser) {
    console.log(`✅ Admin user already exists: ${username}`)
  } else {
    const hashed = await bcrypt.hash(password, 10)
    await prisma.user.create({
      data: {
        username,
        password: hashed,
        role: 'admin',
        name: 'Admin',
      },
    })
    console.log(`✅ Created admin user: ${username} / ${password}`)
  }

  // ===== 2. Create Contact Info =====
  const existingContact = await prisma.contactInfo.findFirst()
  if (existingContact) {
    console.log('✅ Contact info already exists')
  } else {
    await prisma.contactInfo.create({
      data: {
        phone: '03-5551234',
        phoneLink: 'tel:035551234',
        email: 'info@apartment-realty.co.il',
        emailLink: 'mailto:info@apartment-realty.co.il',
        address: 'רחוב סוקולוב 50',
        city: 'חולון',
        mapUrl: 'https://maps.google.com/?q=32.0167,34.7794',
        weekdayHours: 'ראשון - חמישי: 9:00 - 18:00',
        fridayHours: 'שישי: 9:00 - 13:00',
        facebook: 'https://facebook.com/apartment-realty',
        instagram: 'https://instagram.com/apartment-realty',
        linkedin: 'https://linkedin.com/company/apartment-realty',
      },
    })
    console.log('✅ Created contact info')
  }

  // ===== 3. Create Sample Properties =====
  const existingProperties = await prisma.property.count()
  if (existingProperties > 0) {
    console.log(`✅ Properties already exist (${existingProperties} found)`)
  } else {
    const properties = [
      {
        dealType: 'sale',
        city: 'holon',
        neighborhood: 'נאות רחל',
        street: 'רחוב סוקולוב',
        streetNumber: '45',
        apartmentNumber: '12',
        latitude: 32.0167,
        longitude: 34.7794,
        propertyType: 'apartment',
        floor: 4,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['south', 'east']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 100,
        builtArea: 95,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים מרווחת בחולון',
        description: 'דירת 4 חדרים יפהפייה ומרווחת בשכונת נאות רחל, חולון. הדירה משופצת לחלוטין עם מטבח מעוצב, מרפסת שמש גדולה ומעלית. קרובה לפארק, בתי ספר ותחבורה ציבורית. הזדמנות מצוינת למשפחות!',
        price: '₪2,150,000',
        originalPrice: '₪2,300,000',
        images: JSON.stringify(['/uploads/properties/1770668230564-1d730r56ctg.jpeg']),
        status: 'Exclusive',
        location: 'סוקולוב 45, חולון',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'batyam',
        neighborhood: 'מרכז העיר',
        street: 'רחוב הרצל',
        streetNumber: '78',
        apartmentNumber: '5',
        latitude: 32.0236,
        longitude: 34.7515,
        propertyType: 'apartment',
        floor: 2,
        parking: 'none',
        position: 'front-back',
        furniture: 'full',
        directions: JSON.stringify(['west', 'east']),
        kitchen: 'standard',
        rooms: '3',
        area: 75,
        builtArea: 72,
        vacancyDate: '01/03/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת 3 חדרים להשכרה בבת ים',
        description: 'דירת 3 חדרים מרוהטת במלואה במרכז בת ים. מיקום מצוין, קרובה לחוף הים, מרכזי קניות ותחבורה ציבורית. מתאימה לזוגות צעירים או סטודנטים. מיזוג אוויר בכל החדרים.',
        price: '₪4,500/חודש',
        originalPrice: null,
        images: JSON.stringify(['/uploads/properties/1770668235982-4pqhvnsqon.jpeg']),
        status: 'New',
        location: 'הרצל 78, בת ים',
        bedrooms: '3',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'rishon',
        neighborhood: 'נחלת יהודה',
        street: 'רחוב רוטשילד',
        streetNumber: '22',
        apartmentNumber: '8',
        latitude: 31.9730,
        longitude: 34.7925,
        propertyType: 'garden-apartment',
        floor: 0,
        parking: 'double',
        position: 'corner',
        furniture: 'partial',
        directions: JSON.stringify(['south', 'west', 'north']),
        kitchen: 'upgraded',
        rooms: '5',
        area: 140,
        builtArea: 130,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת גן מפוארת 5 חדרים בראשון לציון',
        description: 'דירת גן יוקרתית עם גינה פרטית ענקית של 80 מ"ר! 5 חדרים, 2 חניות, מרפסת שמש, מחסן ומיזוג מרכזי. השכונה שקטה ומשפחתית, קרובה לפארקים ולבתי ספר. נגישות מלאה לנכים.',
        price: '₪3,800,000',
        originalPrice: '₪3,950,000',
        images: JSON.stringify(['/uploads/properties/1770668242300-ss0kjvvu5we.png']),
        status: 'Opportunity',
        location: 'רוטשילד 22, ראשון לציון',
        bedrooms: '5',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'telaviv',
        neighborhood: 'פלורנטין',
        street: 'רחוב פלורנטין',
        streetNumber: '33',
        apartmentNumber: '15',
        latitude: 32.0594,
        longitude: 34.7700,
        propertyType: 'apartment',
        floor: 5,
        parking: 'none',
        position: 'front',
        furniture: 'full',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '2',
        area: 55,
        builtArea: 52,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: false,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 2 חדרים מעוצבת בפלורנטין, תל אביב',
        description: 'דירת סטודיו מעוצבת ומרוהטת בלב פלורנטין! מיקום מרכזי, קרובה לבתי קפה, ברים ותחבורה ציבורית. קומה 5 עם מעלית ונוף לים. מושלמת לצעירים ומקצוענים.',
        price: '₪6,200/חודש',
        originalPrice: null,
        images: JSON.stringify(['/uploads/properties/1770668392799-11n1mvmji1oj.jpeg']),
        status: null,
        location: 'פלורנטין 33, תל אביב',
        bedrooms: '2',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'holon',
        neighborhood: 'קרית שרת',
        street: 'רחוב הבנים',
        streetNumber: '10',
        apartmentNumber: '3',
        latitude: 32.0110,
        longitude: 34.7720,
        propertyType: 'penthouse',
        floor: 8,
        parking: 'double',
        position: 'corner',
        furniture: 'none',
        directions: JSON.stringify(['north', 'south', 'east', 'west']),
        kitchen: 'upgraded',
        rooms: '6',
        area: 200,
        builtArea: 180,
        vacancyDate: '01/06/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'פנטהאוז מדהים 6 חדרים בחולון',
        description: 'פנטהאוז יוקרתי עם נוף פנורמי מרהיב! 6 חדרים, מרפסת ענקית, 2 חניות, מעלית ישירה לדירה. מטבח שף מעוצב, סלון ענק עם תקרות גבוהות. הדירה המושלמת למשפחות גדולות.',
        price: '₪5,500,000',
        originalPrice: null,
        images: JSON.stringify(['/uploads/properties/1770668544513-j6n5oe8xi1h.jpeg']),
        status: 'Exclusive',
        location: 'הבנים 10, חולון',
        bedrooms: '6',
        bathrooms: 3,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'batyam',
        neighborhood: 'חוף הים',
        street: 'רחוב בן גוריון',
        streetNumber: '55',
        apartmentNumber: '10',
        latitude: 32.0200,
        longitude: 34.7400,
        propertyType: 'apartment',
        floor: 7,
        parking: 'yes',
        position: 'front',
        furniture: 'partial',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '3',
        area: 85,
        builtArea: 80,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים עם נוף לים בבת ים',
        description: 'דירת 3 חדרים מהממת עם נוף ישיר לים! קומה 7 עם מעלית, מרפסת שמש עם שקיעות מדהימות. מטבח מעוצב, מחסן וחניה. מרחק הליכה מהחוף. הזדמנות נדירה!',
        price: '₪2,700,000',
        originalPrice: '₪2,850,000',
        images: JSON.stringify(['/uploads/properties/1770668548335-itqh4qvoawk.png']),
        status: 'New',
        location: 'בן גוריון 55, בת ים',
        bedrooms: '3',
        bathrooms: 1,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'rishon',
        neighborhood: 'מזרח',
        street: 'רחוב ז׳בוטינסקי',
        streetNumber: '14',
        apartmentNumber: '2',
        latitude: 31.9690,
        longitude: 34.8050,
        propertyType: 'cottage',
        floor: 0,
        parking: 'double',
        position: 'corner',
        furniture: 'none',
        directions: JSON.stringify(['north', 'east']),
        kitchen: 'upgraded',
        rooms: '5',
        area: 180,
        builtArea: 170,
        vacancyDate: '15/03/2026',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: "קוטג' 5 חדרים להשכרה בראשון לציון",
        description: "קוטג' מרווח ומפואר להשכרה בשכונת מזרח, ראשון לציון. 5 חדרים, גינה פרטית, 2 חניות, מרפסות מרווחות. מתאים למשפחות גדולות. אזור שקט ומשפחתי עם גישה נוחה לכבישים ראשיים.",
        price: '₪9,500/חודש',
        originalPrice: '₪10,000/חודש',
        images: JSON.stringify([]),
        status: 'Opportunity',
        location: "ז'בוטינסקי 14, ראשון לציון",
        bedrooms: '5',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'telaviv',
        neighborhood: 'יפו',
        street: 'רחוב יפת',
        streetNumber: '100',
        apartmentNumber: '4',
        latitude: 32.0505,
        longitude: 34.7568,
        propertyType: 'apartment',
        floor: 3,
        parking: 'yes',
        position: 'back',
        furniture: 'partial',
        directions: JSON.stringify(['east', 'south']),
        kitchen: 'standard',
        rooms: '3',
        area: 70,
        builtArea: 68,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים ביפו ההיסטורית',
        description: 'דירה מקסימה בלב יפו העתיקה! 3 חדרים עם אופי ייחודי, קרובה לשוק הפשפשים, מסעדות ובתי קפה. בניין משוחזר עם מעלית. מתאימה למשקיעים או לזוגות שאוהבים אווירה.',
        price: '₪2,400,000',
        originalPrice: null,
        images: JSON.stringify([]),
        status: null,
        location: 'יפת 100, תל אביב-יפו',
        bedrooms: '3',
        bathrooms: 1,
        category: 'sales',
        isActive: true,
      },
    ]

    for (const property of properties) {
      await prisma.property.create({ data: property })
    }

    console.log(`✅ Created ${properties.length} sample properties`)
  }

  console.log('\n🎉 Seed completed successfully!')
  console.log('\n📋 Summary:')
  console.log(`   Users: ${await prisma.user.count()}`)
  console.log(`   Properties: ${await prisma.property.count()}`)
  console.log(`   Contact Info: ${await prisma.contactInfo.count()}`)
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
