import { PrismaClient } from '@prisma/client'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'
import bcrypt from 'bcryptjs'
import dotenv from 'dotenv'

// Load environment variables
dotenv.config()

// Use DATABASE_URL from environment, fallback to default
const databaseUrl = process.env.DATABASE_URL || 'file:./dev.db'
console.log('📦 Database URL:', databaseUrl)

const adapter = new PrismaBetterSqlite3({ url: databaseUrl })
const prisma = new PrismaClient({ adapter })

const username = process.env.ADMIN_USERNAME || 'admin'
// Don't hardcode real credentials; keep the default obviously non-production.
const password = process.env.ADMIN_PASSWORD || 'change-me'

async function main() {
  console.log('🌱 Starting seed...\n')

  // ===== 1. Create Admin User =====
  const existingUser = await prisma.user.findUnique({ where: { username } })
  if (existingUser) {
    console.log(`✅ Admin user already exists: ${username}`)
  } else {
    const hashed = await bcrypt.hash(password, 10)
    await prisma.user.create({
      data: {
        username,
        password: hashed,
        role: 'admin',
        name: 'Admin',
      },
    })
    console.log(`✅ Created admin user: ${username} / ${password}`)
  }

  // ===== 2. Create Contact Info =====
  const existingContact = await prisma.contactInfo.findFirst()
  if (existingContact) {
    console.log('✅ Contact info already exists')
  } else {
    await prisma.contactInfo.create({
      data: {
        phone: '03-5551234',
        phoneLink: 'tel:035551234',
        email: 'info@apartment-realty.co.il',
        emailLink: 'mailto:info@apartment-realty.co.il',
        address: 'רחוב סוקולוב 50',
        city: 'חולון',
        mapUrl: 'https://maps.google.com/?q=32.0167,34.7794',
        weekdayHours: 'ראשון - חמישי: 9:00 - 18:00',
        fridayHours: 'שישי: 9:00 - 13:00',
        facebook: 'https://facebook.com/apartment-realty',
        instagram: 'https://instagram.com/apartment-realty',
        linkedin: 'https://linkedin.com/company/apartment-realty',
      },
    })
    console.log('✅ Created contact info')
  }

  // ===== 3. Create Sample Properties =====
  const existingProperties = await prisma.property.count()
  if (existingProperties > 0) {
    console.log(`✅ Properties already exist (${existingProperties} found)`)
    console.log('🔄 Clearing existing properties to add new ones...')
    await prisma.property.deleteMany({})
    console.log('✅ Cleared existing properties')
  }
  
  // Image URLs for Israeli apartments - prioritize local images
  const israelApartmentImages = [
    '/images/hero/sales.jpg', // Local image
    '/images/hero/rentals.webp', // Local image
    '/images/hero/rent.png', // Local image
    '/images/hero/main-hero.jpg', // Local image
    '/images/hero/other-hero.jpeg', // Local image
    '/images/hero/aboutus.png', // Local image
    '/images/minimalist-tel-aviv-apartment.jpg', // Local image
    '/images/LuxuryLiving.jpg', // Local image
    '/images/buildings.jpeg', // Local image
    '/images/apartment.jpg', // Local image
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Modern apartment interior
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Living room
    'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Kitchen
    'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Bedroom
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Apartment building
    'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Modern apartment
    'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Balcony view
    'https://images.unsplash.com/photo-1556912172-45b7abe8b7e4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Bathroom
    'https://images.unsplash.com/photo-1556911220-bff31c812dba?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Kitchen modern
    'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Living space
    'https://images.unsplash.com/photo-1554995207-c18c203602cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Apartment interior
    'https://images.unsplash.com/photo-1556912173-6719d91a3d3c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Modern design
    'https://images.unsplash.com/photo-1556911220-ef6b2e4c0e5a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Cozy apartment
    'https://images.unsplash.com/photo-1560448075-cbc16ba4ae9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Spacious room
    'https://images.unsplash.com/photo-1560448205-97abe736d2e0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Luxury apartment
    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Modern living room
    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Apartment interior
    'https://images.unsplash.com/photo-1560448075-cbc16ba4ae9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Spacious apartment
    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', // Building exterior
  ]

  const properties = [
      {
        dealType: 'sale',
        city: 'holon',
        neighborhood: 'נאות רחל',
        street: 'רחוב סוקולוב',
        streetNumber: '45',
        apartmentNumber: '12',
        latitude: 32.0167,
        longitude: 34.7794,
        propertyType: 'apartment',
        floor: 4,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['south', 'east']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 100,
        builtArea: 95,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים מרווחת בחולון',
        description: 'דירת 4 חדרים יפהפייה ומרווחת בשכונת נאות רחל, חולון. הדירה משופצת לחלוטין עם מטבח מעוצב, מרפסת שמש גדולה ומעלית. קרובה לפארק, בתי ספר ותחבורה ציבורית. הזדמנות מצוינת למשפחות!',
        price: '₪2,150,000',
        originalPrice: '₪2,300,000',
        totalFloors: 8,
        images: JSON.stringify([israelApartmentImages[0], israelApartmentImages[1], israelApartmentImages[2]]),
        status: 'Exclusive',
        location: 'סוקולוב 45, חולון',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'batyam',
        neighborhood: 'מרכז העיר',
        street: 'רחוב הרצל',
        streetNumber: '78',
        apartmentNumber: '5',
        latitude: 32.0236,
        longitude: 34.7515,
        propertyType: 'apartment',
        floor: 2,
        parking: 'none',
        position: 'front-back',
        furniture: 'full',
        directions: JSON.stringify(['west', 'east']),
        kitchen: 'standard',
        rooms: '3',
        area: 75,
        builtArea: 72,
        vacancyDate: '01/03/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת 3 חדרים להשכרה בבת ים',
        description: 'דירת 3 חדרים מרוהטת במלואה במרכז בת ים. מיקום מצוין, קרובה לחוף הים, מרכזי קניות ותחבורה ציבורית. מתאימה לזוגות צעירים או סטודנטים. מיזוג אוויר בכל החדרים.',
        price: '₪4,500/חודש',
        originalPrice: null,
        totalFloors: 5,
        images: JSON.stringify([israelApartmentImages[3], israelApartmentImages[4]]),
        status: 'New',
        location: 'הרצל 78, בת ים',
        bedrooms: '3',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'rishon',
        neighborhood: 'נחלת יהודה',
        street: 'רחוב רוטשילד',
        streetNumber: '22',
        apartmentNumber: '8',
        latitude: 31.9730,
        longitude: 34.7925,
        propertyType: 'garden-apartment',
        floor: 0,
        parking: 'double',
        position: 'corner',
        furniture: 'partial',
        directions: JSON.stringify(['south', 'west', 'north']),
        kitchen: 'upgraded',
        rooms: '5',
        area: 140,
        builtArea: 130,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת גן מפוארת 5 חדרים בראשון לציון',
        description: 'דירת גן יוקרתית עם גינה פרטית ענקית של 80 מ"ר! 5 חדרים, 2 חניות, מרפסת שמש, מחסן ומיזוג מרכזי. השכונה שקטה ומשפחתית, קרובה לפארקים ולבתי ספר. נגישות מלאה לנכים.',
        price: '₪3,800,000',
        originalPrice: '₪3,950,000',
        totalFloors: 2,
        images: JSON.stringify([israelApartmentImages[5], israelApartmentImages[6], israelApartmentImages[7]]),
        status: 'Opportunity',
        location: 'רוטשילד 22, ראשון לציון',
        bedrooms: '5',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'telaviv',
        neighborhood: 'פלורנטין',
        street: 'רחוב פלורנטין',
        streetNumber: '33',
        apartmentNumber: '15',
        latitude: 32.0594,
        longitude: 34.7700,
        propertyType: 'apartment',
        floor: 5,
        parking: 'none',
        position: 'front',
        furniture: 'full',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '2',
        area: 55,
        builtArea: 52,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: false,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 2 חדרים מעוצבת בפלורנטין, תל אביב',
        description: 'דירת סטודיו מעוצבת ומרוהטת בלב פלורנטין! מיקום מרכזי, קרובה לבתי קפה, ברים ותחבורה ציבורית. קומה 5 עם מעלית ונוף לים. מושלמת לצעירים ומקצוענים.',
        price: '₪6,200/חודש',
        originalPrice: null,
        totalFloors: 6,
        images: JSON.stringify([israelApartmentImages[8], israelApartmentImages[9]]),
        status: null,
        location: 'פלורנטין 33, תל אביב',
        bedrooms: '2',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'holon',
        neighborhood: 'קרית שרת',
        street: 'רחוב הבנים',
        streetNumber: '10',
        apartmentNumber: '3',
        latitude: 32.0110,
        longitude: 34.7720,
        propertyType: 'penthouse',
        floor: 8,
        parking: 'double',
        position: 'corner',
        furniture: 'none',
        directions: JSON.stringify(['north', 'south', 'east', 'west']),
        kitchen: 'upgraded',
        rooms: '6',
        area: 200,
        builtArea: 180,
        vacancyDate: '01/06/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'פנטהאוז מדהים 6 חדרים בחולון',
        description: 'פנטהאוז יוקרתי עם נוף פנורמי מרהיב! 6 חדרים, מרפסת ענקית, 2 חניות, מעלית ישירה לדירה. מטבח שף מעוצב, סלון ענק עם תקרות גבוהות. הדירה המושלמת למשפחות גדולות.',
        price: '₪5,500,000',
        originalPrice: null,
        totalFloors: 8,
        images: JSON.stringify([israelApartmentImages[10], israelApartmentImages[11], israelApartmentImages[12]]),
        status: 'Exclusive',
        location: 'הבנים 10, חולון',
        bedrooms: '6',
        bathrooms: 3,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'batyam',
        neighborhood: 'חוף הים',
        street: 'רחוב בן גוריון',
        streetNumber: '55',
        apartmentNumber: '10',
        latitude: 32.0200,
        longitude: 34.7400,
        propertyType: 'apartment',
        floor: 7,
        parking: 'yes',
        position: 'front',
        furniture: 'partial',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '3',
        area: 85,
        builtArea: 80,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים עם נוף לים בבת ים',
        description: 'דירת 3 חדרים מהממת עם נוף ישיר לים! קומה 7 עם מעלית, מרפסת שמש עם שקיעות מדהימות. מטבח מעוצב, מחסן וחניה. מרחק הליכה מהחוף. הזדמנות נדירה!',
        price: '₪2,700,000',
        originalPrice: '₪2,850,000',
        totalFloors: 10,
        images: JSON.stringify([israelApartmentImages[13], israelApartmentImages[14], israelApartmentImages[0]]),
        status: 'New',
        location: 'בן גוריון 55, בת ים',
        bedrooms: '3',
        bathrooms: 1,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'rishon',
        neighborhood: 'מזרח',
        street: 'רחוב ז׳בוטינסקי',
        streetNumber: '14',
        apartmentNumber: '2',
        latitude: 31.9690,
        longitude: 34.8050,
        propertyType: 'cottage',
        floor: 0,
        parking: 'double',
        position: 'corner',
        furniture: 'none',
        directions: JSON.stringify(['north', 'east']),
        kitchen: 'upgraded',
        rooms: '5',
        area: 180,
        builtArea: 170,
        vacancyDate: '15/03/2026',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: "קוטג' 5 חדרים להשכרה בראשון לציון",
        description: "קוטג' מרווח ומפואר להשכרה בשכונת מזרח, ראשון לציון. 5 חדרים, גינה פרטית, 2 חניות, מרפסות מרווחות. מתאים למשפחות גדולות. אזור שקט ומשפחתי עם גישה נוחה לכבישים ראשיים.",
        price: '₪9,500/חודש',
        originalPrice: '₪10,000/חודש',
        totalFloors: 1,
        images: JSON.stringify([israelApartmentImages[1], israelApartmentImages[2]]),
        status: 'Opportunity',
        location: "ז'בוטינסקי 14, ראשון לציון",
        bedrooms: '5',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'telaviv',
        neighborhood: 'יפו',
        street: 'רחוב יפת',
        streetNumber: '100',
        apartmentNumber: '4',
        latitude: 32.0505,
        longitude: 34.7568,
        propertyType: 'apartment',
        floor: 3,
        parking: 'yes',
        position: 'back',
        furniture: 'partial',
        directions: JSON.stringify(['east', 'south']),
        kitchen: 'standard',
        rooms: '3',
        area: 70,
        builtArea: 68,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים ביפו ההיסטורית',
        description: 'דירה מקסימה בלב יפו העתיקה! 3 חדרים עם אופי ייחודי, קרובה לשוק הפשפשים, מסעדות ובתי קפה. בניין משוחזר עם מעלית. מתאימה למשקיעים או לזוגות שאוהבים אווירה.',
        price: '₪2,400,000',
        originalPrice: null,
        totalFloors: 5,
        images: JSON.stringify([israelApartmentImages[3], israelApartmentImages[4]]),
        status: null,
        location: 'יפת 100, תל אביב-יפו',
        bedrooms: '3',
        bathrooms: 1,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'telaviv',
        neighborhood: 'רמת אביב',
        street: 'רחוב אבן גבירול',
        streetNumber: '120',
        apartmentNumber: '7',
        latitude: 32.0853,
        longitude: 34.7818,
        propertyType: 'apartment',
        floor: 6,
        totalFloors: 12,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['north', 'west']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 110,
        builtArea: 105,
        vacancyDate: '01/04/2026',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים יוקרתית ברמת אביב',
        description: 'דירה מפוארת במיקום פנומנלי ברמת אביב! 4 חדרים, קומה 6 עם נוף מרהיב, מטבח שף, מרפסת שמש גדולה. קרובה לפארק הירקון, קניונים ובתי ספר יוקרתיים. בניין חדש עם מערכת אבטחה.',
        price: '₪4,200,000',
        originalPrice: '₪4,500,000',
        images: JSON.stringify([israelApartmentImages[5], israelApartmentImages[6], israelApartmentImages[7], israelApartmentImages[8]]),
        status: 'Exclusive',
        location: 'אבן גבירול 120, תל אביב',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'holon',
        neighborhood: 'קרית אילון',
        street: 'רחוב הרצל',
        streetNumber: '25',
        apartmentNumber: '9',
        latitude: 32.0080,
        longitude: 34.7850,
        propertyType: 'apartment',
        floor: 3,
        totalFloors: 6,
        parking: 'yes',
        position: 'front-back',
        furniture: 'full',
        directions: JSON.stringify(['south', 'north']),
        kitchen: 'upgraded',
        rooms: '3.5',
        area: 90,
        builtArea: 85,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3.5 חדרים מרוהטת בחולון',
        description: 'דירה מעוצבת ומרוהטת במלואה בקרית אילון. מיקום שקט, קרוב לפארקים, בתי ספר ומרכזי קניות. מיזוג מרכזי, מטבח מעוצב, מרפסת שמש. מושלמת למשפחות צעירות.',
        price: '₪5,800/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[9], israelApartmentImages[10]]),
        status: 'New',
        location: 'הרצל 25, חולון',
        bedrooms: '3.5',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'batyam',
        neighborhood: 'רמת יוסף',
        street: 'רחוב רוטשילד',
        streetNumber: '88',
        apartmentNumber: '12',
        latitude: 32.0150,
        longitude: 34.7450,
        propertyType: 'apartment',
        floor: 4,
        totalFloors: 7,
        parking: 'yes',
        position: 'corner',
        furniture: 'partial',
        directions: JSON.stringify(['west', 'south']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 95,
        builtArea: 90,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים עם נוף בבת ים',
        description: 'דירה יפה ומרווחת ברמת יוסף, בת ים. 4 חדרים, קומה 4 עם נוף, מרפסת שמש, מטבח מעוצב. קרובה לחוף הים, פארקים ובתי ספר. אזור שקט ומשפחתי.',
        price: '₪2,550,000',
        originalPrice: '₪2,700,000',
        images: JSON.stringify([israelApartmentImages[11], israelApartmentImages[12]]),
        status: 'Opportunity',
        location: 'רוטשילד 88, בת ים',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'telaviv',
        neighborhood: 'נווה צדק',
        street: 'רחוב שבזי',
        streetNumber: '15',
        apartmentNumber: '3',
        latitude: 32.0620,
        longitude: 34.7650,
        propertyType: 'apartment',
        floor: 2,
        totalFloors: 4,
        parking: 'none',
        position: 'front',
        furniture: 'full',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '2',
        area: 60,
        builtArea: 58,
        vacancyDate: '01/05/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת 2 חדרים בנווה צדק ההיסטורית',
        description: 'דירה מקסימה בלב נווה צדק! 2 חדרים עם אופי ייחודי, קרובה לחוף, מסעדות ובתי קפה. דירה מרוהטת במלואה, מעוצבת בסגנון בוטיק. מושלמת לזוגות או מקצוענים.',
        price: '₪7,500/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[13], israelApartmentImages[14]]),
        status: null,
        location: 'שבזי 15, תל אביב',
        bedrooms: '2',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'rishon',
        neighborhood: 'מרכז העיר',
        street: 'רחוב הרצל',
        streetNumber: '50',
        apartmentNumber: '5',
        latitude: 31.9650,
        longitude: 34.8000,
        propertyType: 'apartment',
        floor: 5,
        totalFloors: 8,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['south', 'east']),
        kitchen: 'upgraded',
        rooms: '3.5',
        area: 88,
        builtArea: 85,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3.5 חדרים במרכז ראשון לציון',
        description: 'דירה מעולה במיקום מרכזי! 3.5 חדרים, קומה 5, מרפסת שמש, מטבח מעוצב. קרובה לכל השירותים, קניונים, בתי ספר ותחבורה ציבורית. בניין חדש עם מעלית.',
        price: '₪2,300,000',
        originalPrice: '₪2,450,000',
        images: JSON.stringify([israelApartmentImages[0], israelApartmentImages[1], israelApartmentImages[2]]),
        status: 'New',
        location: 'הרצל 50, ראשון לציון',
        bedrooms: '3.5',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'holon',
        neighborhood: 'קרית משה',
        street: 'רחוב ויצמן',
        streetNumber: '30',
        apartmentNumber: '8',
        latitude: 32.0130,
        longitude: 34.7780,
        propertyType: 'apartment',
        floor: 1,
        totalFloors: 4,
        parking: 'yes',
        position: 'back',
        furniture: 'partial',
        directions: JSON.stringify(['north']),
        kitchen: 'standard',
        rooms: '3',
        area: 80,
        builtArea: 75,
        vacancyDate: '15/04/2026',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: false,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים בקרית משה, חולון',
        description: 'דירה נעימה בקרית משה. 3 חדרים, קומה 1 עם גישה נוחה, חניה, מחסן. מיקום שקט, קרוב לפארקים ובתי ספר. מתאימה למשפחות או זוגות.',
        price: '₪4,200/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[3], israelApartmentImages[4]]),
        status: null,
        location: 'ויצמן 30, חולון',
        bedrooms: '3',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'batyam',
        neighborhood: 'רמת הנשיא',
        street: 'רחוב נורדאו',
        streetNumber: '42',
        apartmentNumber: '6',
        latitude: 32.0180,
        longitude: 34.7480,
        propertyType: 'apartment',
        floor: 6,
        totalFloors: 9,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 105,
        builtArea: 100,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים עם נוף לים בבת ים',
        description: 'דירה מדהימה עם נוף פנורמי לים! 4 חדרים, קומה 6, מרפסת שמש ענקית, מטבח שף. קרובה לחוף, פארקים וכל השירותים. בניין חדש עם מערכת אבטחה.',
        price: '₪3,100,000',
        originalPrice: '₪3,300,000',
        images: JSON.stringify([israelApartmentImages[5], israelApartmentImages[6], israelApartmentImages[7]]),
        status: 'Exclusive',
        location: 'נורדאו 42, בת ים',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'telaviv',
        neighborhood: 'הצפון החדש',
        street: 'רחוב דיזנגוף',
        streetNumber: '200',
        apartmentNumber: '10',
        latitude: 32.0800,
        longitude: 34.7750,
        propertyType: 'apartment',
        floor: 8,
        totalFloors: 15,
        parking: 'yes',
        position: 'corner',
        furniture: 'full',
        directions: JSON.stringify(['north', 'west']),
        kitchen: 'upgraded',
        rooms: '3',
        area: 85,
        builtArea: 82,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים יוקרתית בצפון תל אביב',
        description: 'דירה מפוארת בצפון תל אביב! 3 חדרים, קומה 8 עם נוף מרהיב, מרפסת שמש, מטבח מעוצב. קרובה לפארק הירקון, קניונים וכל השירותים. בניין יוקרתי עם שירותים מלאים.',
        price: '₪12,000/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[8], israelApartmentImages[9], israelApartmentImages[10]]),
        status: 'New',
        location: 'דיזנגוף 200, תל אביב',
        bedrooms: '3',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'rishon',
        neighborhood: 'קרית ראשון',
        street: 'רחוב הרצל',
        streetNumber: '100',
        apartmentNumber: '15',
        latitude: 31.9700,
        longitude: 34.7950,
        propertyType: 'garden-apartment',
        floor: 0,
        totalFloors: 2,
        parking: 'double',
        position: 'corner',
        furniture: 'partial',
        directions: JSON.stringify(['south', 'east', 'west']),
        kitchen: 'upgraded',
        rooms: '5',
        area: 150,
        builtArea: 140,
        vacancyDate: '01/07/2026',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת גן מפוארת 5 חדרים בראשון לציון',
        description: 'דירת גן יוקרתית עם גינה פרטית של 100 מ"ר! 5 חדרים, 2 חניות, מרפסת שמש ענקית, מחסן. השכונה שקטה ומשפחתית, קרובה לפארקים ולכל השירותים.',
        price: '₪3,950,000',
        originalPrice: '₪4,200,000',
        images: JSON.stringify([israelApartmentImages[11], israelApartmentImages[12], israelApartmentImages[13]]),
        status: 'Opportunity',
        location: 'הרצל 100, ראשון לציון',
        bedrooms: '5',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'holon',
        neighborhood: 'קרית עתידים',
        street: 'רחוב בן גוריון',
        streetNumber: '15',
        apartmentNumber: '4',
        latitude: 32.0100,
        longitude: 34.7800,
        propertyType: 'apartment',
        floor: 3,
        totalFloors: 5,
        parking: 'yes',
        position: 'front',
        furniture: 'full',
        directions: JSON.stringify(['south', 'east']),
        kitchen: 'upgraded',
        rooms: '3.5',
        area: 92,
        builtArea: 88,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3.5 חדרים מרוהטת בחולון',
        description: 'דירה מעוצבת ומרוהטת במלואה! 3.5 חדרים, מטבח מעוצב, מרפסת שמש, חניה. מיקום שקט, קרוב לפארקים ובתי ספר. מושלמת למשפחות.',
        price: '₪5,500/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[14], israelApartmentImages[0], israelApartmentImages[1]]),
        status: null,
        location: 'בן גוריון 15, חולון',
        bedrooms: '3.5',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'telaviv',
        neighborhood: 'הצפון הישן',
        street: 'רחוב גורדון',
        streetNumber: '80',
        apartmentNumber: '12',
        latitude: 32.0820,
        longitude: 34.7780,
        propertyType: 'apartment',
        floor: 4,
        totalFloors: 6,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 115,
        builtArea: 110,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים יוקרתית בתל אביב',
        description: 'דירה מפוארת בצפון תל אביב! 4 חדרים, קומה 4, מרפסת שמש, מטבח שף מעוצב. קרובה לחוף, פארק הירקון וכל השירותים. בניין משופץ עם מעלית.',
        price: '₪4,800,000',
        originalPrice: '₪5,100,000',
        images: JSON.stringify([israelApartmentImages[2], israelApartmentImages[3], israelApartmentImages[4], israelApartmentImages[5]]),
        status: 'Exclusive',
        location: 'גורדון 80, תל אביב',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'batyam',
        neighborhood: 'רמת יוסף',
        street: 'רחוב הרצל',
        streetNumber: '60',
        apartmentNumber: '8',
        latitude: 32.0160,
        longitude: 34.7420,
        propertyType: 'apartment',
        floor: 2,
        totalFloors: 4,
        parking: 'none',
        position: 'back',
        furniture: 'full',
        directions: JSON.stringify(['east']),
        kitchen: 'standard',
        rooms: '2.5',
        area: 65,
        builtArea: 62,
        vacancyDate: '01/06/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת 2.5 חדרים להשכרה בבת ים',
        description: 'דירה נעימה להשכרה בבת ים. 2.5 חדרים, מרוהטת במלואה, מיזוג אוויר. מיקום שקט, קרוב לחוף ולכל השירותים. מתאימה לזוגות או סטודנטים.',
        price: '₪3,800/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[6], israelApartmentImages[7]]),
        status: null,
        location: 'הרצל 60, בת ים',
        bedrooms: '2.5',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'rishon',
        neighborhood: 'קרית ראשון',
        street: 'רחוב ויצמן',
        streetNumber: '75',
        apartmentNumber: '9',
        latitude: 31.9680,
        longitude: 34.7980,
        propertyType: 'apartment',
        floor: 5,
        totalFloors: 7,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['south', 'west']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 98,
        builtArea: 95,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים במרכז ראשון לציון',
        description: 'דירה מעולה במיקום מרכזי! 4 חדרים, קומה 5, מרפסת שמש, מטבח מעוצב, חניה. קרובה לכל השירותים, קניונים ובתי ספר. בניין חדש עם מעלית.',
        price: '₪2,450,000',
        originalPrice: '₪2,600,000',
        images: JSON.stringify([israelApartmentImages[8], israelApartmentImages[9], israelApartmentImages[10]]),
        status: 'New',
        location: 'ויצמן 75, ראשון לציון',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'telaviv',
        neighborhood: 'הדר יוסף',
        street: 'רחוב אבן גבירול',
        streetNumber: '150',
        apartmentNumber: '6',
        latitude: 32.0880,
        longitude: 34.7830,
        propertyType: 'apartment',
        floor: 7,
        totalFloors: 10,
        parking: 'yes',
        position: 'corner',
        furniture: 'partial',
        directions: JSON.stringify(['north', 'east']),
        kitchen: 'upgraded',
        rooms: '3',
        area: 90,
        builtArea: 87,
        vacancyDate: '15/05/2026',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים יוקרתית בהדר יוסף',
        description: 'דירה מפוארת בהדר יוסף! 3 חדרים, קומה 7 עם נוף, מרפסת שמש, מטבח מעוצב, חניה. קרובה לפארק הירקון וכל השירותים. בניין יוקרתי.',
        price: '₪10,500/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[11], israelApartmentImages[12]]),
        status: 'New',
        location: 'אבן גבירול 150, תל אביב',
        bedrooms: '3',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'holon',
        neighborhood: 'קרית שרת',
        street: 'רחוב סוקולוב',
        streetNumber: '80',
        apartmentNumber: '11',
        latitude: 32.0120,
        longitude: 34.7740,
        propertyType: 'apartment',
        floor: 6,
        totalFloors: 9,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['south', 'east']),
        kitchen: 'upgraded',
        rooms: '5',
        area: 125,
        builtArea: 120,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: true,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 5 חדרים מרווחת בחולון',
        description: 'דירה מרווחת ומפוארת! 5 חדרים, קומה 6, מרפסת שמש ענקית, מטבח שף, 2 חניות. מיקום שקט, קרוב לפארקים ולכל השירותים. בניין חדש.',
        price: '₪3,200,000',
        originalPrice: '₪3,400,000',
        images: JSON.stringify([israelApartmentImages[13], israelApartmentImages[14], israelApartmentImages[0], israelApartmentImages[1]]),
        status: 'Exclusive',
        location: 'סוקולוב 80, חולון',
        bedrooms: '5',
        bathrooms: 3,
        category: 'sales',
        isActive: true,
        isPinned: true,
      },
      {
        dealType: 'rent',
        city: 'batyam',
        neighborhood: 'חוף הים',
        street: 'רחוב בן גוריון',
        streetNumber: '90',
        apartmentNumber: '14',
        latitude: 32.0220,
        longitude: 34.7380,
        propertyType: 'apartment',
        floor: 8,
        totalFloors: 12,
        parking: 'yes',
        position: 'front',
        furniture: 'full',
        directions: JSON.stringify(['west']),
        kitchen: 'upgraded',
        rooms: '3',
        area: 82,
        builtArea: 78,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים עם נוף לים בבת ים',
        description: 'דירה מדהימה עם נוף ישיר לים! 3 חדרים, קומה 8, מרפסת שמש עם שקיעות, מטבח מעוצב, חניה. מרחק הליכה מהחוף. הזדמנות נדירה!',
        price: '₪6,500/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[2], israelApartmentImages[3], israelApartmentImages[4]]),
        status: 'New',
        location: 'בן גוריון 90, בת ים',
        bedrooms: '3',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'rishon',
        neighborhood: 'נחלת יהודה',
        street: 'רחוב רוטשילד',
        streetNumber: '45',
        apartmentNumber: '7',
        latitude: 31.9740,
        longitude: 34.7900,
        propertyType: 'apartment',
        floor: 3,
        totalFloors: 5,
        parking: 'yes',
        position: 'back',
        furniture: 'partial',
        directions: JSON.stringify(['north', 'east']),
        kitchen: 'standard',
        rooms: '3',
        area: 78,
        builtArea: 75,
        vacancyDate: '01/08/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3 חדרים בראשון לציון',
        description: 'דירה נעימה בנחלת יהודה. 3 חדרים, קומה 3, מטבח, חניה, מחסן. מיקום שקט, קרוב לפארקים ולכל השירותים. מתאימה למשפחות.',
        price: '₪1,950,000',
        originalPrice: '₪2,100,000',
        images: JSON.stringify([israelApartmentImages[5], israelApartmentImages[6]]),
        status: null,
        location: 'רוטשילד 45, ראשון לציון',
        bedrooms: '3',
        bathrooms: 1,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'telaviv',
        neighborhood: 'רמת אביב ג',
        street: 'רחוב אבן גבירול',
        streetNumber: '180',
        apartmentNumber: '8',
        latitude: 32.0900,
        longitude: 34.7850,
        propertyType: 'apartment',
        floor: 5,
        totalFloors: 8,
        parking: 'yes',
        position: 'front',
        furniture: 'full',
        directions: JSON.stringify(['north', 'west']),
        kitchen: 'upgraded',
        rooms: '3.5',
        area: 95,
        builtArea: 92,
        vacancyDate: 'מיידי',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3.5 חדרים יוקרתית ברמת אביב',
        description: 'דירה מפוארת ברמת אביב! 3.5 חדרים, קומה 5, מרפסת שמש, מטבח שף, חניה. קרובה לפארק הירקון, קניונים וכל השירותים. בניין יוקרתי.',
        price: '₪11,500/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[7], israelApartmentImages[8], israelApartmentImages[9]]),
        status: 'New',
        location: 'אבן גבירול 180, תל אביב',
        bedrooms: '3.5',
        bathrooms: 2,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'holon',
        neighborhood: 'קרית אילון',
        street: 'רחוב הרצל',
        streetNumber: '35',
        apartmentNumber: '13',
        latitude: 32.0090,
        longitude: 34.7860,
        propertyType: 'apartment',
        floor: 4,
        totalFloors: 6,
        parking: 'yes',
        position: 'corner',
        furniture: 'none',
        directions: JSON.stringify(['south', 'west', 'north']),
        kitchen: 'upgraded',
        rooms: '4',
        area: 108,
        builtArea: 105,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: true,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 4 חדרים בקרית אילון, חולון',
        description: 'דירה מעולה בקרית אילון! 4 חדרים, קומה 4, מרפסת שמש, מטבח מעוצב, חניה. מיקום שקט, קרוב לפארקים ולכל השירותים. בניין חדש עם מעלית.',
        price: '₪2,350,000',
        originalPrice: '₪2,500,000',
        images: JSON.stringify([israelApartmentImages[10], israelApartmentImages[11], israelApartmentImages[12]]),
        status: 'Opportunity',
        location: 'הרצל 35, חולון',
        bedrooms: '4',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
      {
        dealType: 'rent',
        city: 'batyam',
        neighborhood: 'רמת יוסף',
        street: 'רחוב נורדאו',
        streetNumber: '25',
        apartmentNumber: '5',
        latitude: 32.0170,
        longitude: 34.7470,
        propertyType: 'apartment',
        floor: 3,
        totalFloors: 5,
        parking: 'none',
        position: 'back',
        furniture: 'partial',
        directions: JSON.stringify(['east']),
        kitchen: 'standard',
        rooms: '2.5',
        area: 68,
        builtArea: 65,
        vacancyDate: '01/07/2026',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: false,
        hasStorage: false,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: false,
        title: 'דירת 2.5 חדרים להשכרה בבת ים',
        description: 'דירה נעימה להשכרה. 2.5 חדרים, מיקום שקט, קרוב לחוף ולכל השירותים. מתאימה לזוגות או סטודנטים.',
        price: '₪3,500/חודש',
        originalPrice: null,
        images: JSON.stringify([israelApartmentImages[13], israelApartmentImages[14]]),
        status: null,
        location: 'נורדאו 25, בת ים',
        bedrooms: '2.5',
        bathrooms: 1,
        category: 'rentals',
        isActive: true,
      },
      {
        dealType: 'sale',
        city: 'telaviv',
        neighborhood: 'יפו',
        street: 'רחוב יפת',
        streetNumber: '120',
        apartmentNumber: '9',
        latitude: 32.0515,
        longitude: 34.7570,
        propertyType: 'apartment',
        floor: 4,
        totalFloors: 6,
        parking: 'yes',
        position: 'front',
        furniture: 'none',
        directions: JSON.stringify(['west', 'south']),
        kitchen: 'upgraded',
        rooms: '3.5',
        area: 92,
        builtArea: 88,
        vacancyDate: 'גמיש',
        hasAirConditioning: true,
        hasDisabledAccess: false,
        hasSunBalcony: true,
        hasStorage: true,
        hasSunroom: false,
        hasBoiler: true,
        hasSafeRoom: true,
        hasElevator: true,
        title: 'דירת 3.5 חדרים ביפו ההיסטורית',
        description: 'דירה מקסימה בלב יפו העתיקה! 3.5 חדרים עם אופי ייחודי, קרובה לשוק הפשפשים, מסעדות ובתי קפה. בניין משוחזר עם מעלית. מתאימה למשקיעים או לזוגות.',
        price: '₪2,650,000',
        originalPrice: '₪2,800,000',
        images: JSON.stringify([israelApartmentImages[0], israelApartmentImages[1], israelApartmentImages[2]]),
        status: 'Opportunity',
        location: 'יפת 120, תל אביב-יפו',
        bedrooms: '3.5',
        bathrooms: 2,
        category: 'sales',
        isActive: true,
      },
    ]

  for (const property of properties) {
    await prisma.property.create({ data: property })
  }

  console.log(`✅ Created ${properties.length} sample properties`)

  // ===== 4. Create Homepage Settings =====
  const existingHomepageSettings = await prisma.homepageSettings.findFirst()
  if (existingHomepageSettings) {
    console.log('✅ Homepage settings already exist')
  } else {
    await prisma.homepageSettings.create({
      data: {
        hotPropositionsTitle: 'הצעות חמות',
        featuredPropertiesTitle: 'נכסים באיזור המרכז',
        featuredPropertiesSubtitle: 'מגוון דירות למכירה ולהשכרה אטרקטיביות באיזור המרכז',
        valuesSectionTitle: 'למה לבחור בנו?',
        aboutSectionTitle: 'אודות',
        processSectionTitle: 'מה חשוב לדעת כשקונים נכס?',
        testimonialsTitle: 'מה הלקוחות שלנו אומרים',
        noCommissionTitle: 'דירה ללא עמלת תיווך',
      },
    })
    console.log('✅ Created homepage settings')
  }

  console.log('\n🎉 Seed completed successfully!')
  console.log('\n📋 Summary:')
  console.log(`   Users: ${await prisma.user.count()}`)
  console.log(`   Properties: ${await prisma.property.count()}`)
  console.log(`   Contact Info: ${await prisma.contactInfo.count()}`)
  console.log(`   Homepage Settings: ${await prisma.homepageSettings.count()}`)
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
